--- 
title: "Introduction to R"
author: "Claudia A Engel"
date: "Last updated: `r format(Sys.time(), '%B %d, %Y')`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: cengel/R-intro
description: "Workshop materials for Intro to R"
---


# Prerequisites {-}

- Geared specifically towards users who are __new__ to R.  
- Have [R](https://cran.r-project.org/) and [RStudio](https://posit.co/download/rstudio-desktop/) installed (see setup instructions below).


## Setup Instructions {-}

[**R**](https://cran.r-project.org/) and [**RStudio**](https://posit.co/download/rstudio-desktop/) are separate downloads and installations. R is the
underlying statistical computing environment. It can be used on its own, but using R alone is no fun. RStudio is a graphical integrated development environment (IDE) that makes using R much easier and more interactive. You need to install R before you launch RStudio. 

Be aware that the most recent version of RStudio requires R version 3.3.0 or later.


### macOS {-}

#### If you already have R and RStudio installed {-}

* Open RStudio, and click on "Help" > "Check for updates". If a new version is
	available, quit RStudio, and download the latest version for RStudio.
* To check the version of R you are using, start RStudio and the first thing
  that appears on the terminal indicates the version of R you are running. Alternatively, you can type `sessionInfo()`, which will also display which version of R you are running. Go on
  the [CRAN website](https://cran.r-project.org/bin/macosx/) and check
  whether a more recent version is available. If so, please download and install
  it.

#### If you don't have R and RStudio installed {-}

* Download R from
  the [CRAN website](http://cran.r-project.org/bin/macosx).
* Select the `.pkg` file for the latest R version. Make sure you choose the appropriate version for your hardware (Apple silicon or Intel) 
* Double click on the downloaded file to install R
* Go to the [RStudio download page](https://posit.co/download/rstudio-desktop/)
* Follow the link to download the latest version under "Install Rstudio" 
* Double click the file to install RStudio
* Once it's installed, open RStudio to make sure it works and you don't get any
  error messages.

### Windows {-}

#### If you already have R and RStudio installed {-}

* Open RStudio, and click on "Help" > "Check for updates". If a new version is
	available, quit RStudio, and download the latest version for RStudio.
* To check which version of R you are using, start RStudio and the first thing
  that appears in the console indicates the version of R you are
  running. Alternatively, you can type `sessionInfo()`, which will also display
  which version of R you are running. Go on
  the [CRAN website](https://cran.r-project.org/bin/windows/base/) and check
  whether a more recent version is available. If so, please download and install
  it. You can [check here](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#How-do-I-UNinstall-R_003f) for
  more information on how to remove old versions from your system if you wish to do so.

#### If you don't have R and RStudio installed {-}

* Download R from
  the [CRAN website](http://cran.r-project.org/bin/windows/base/release.htm).
* Run the `.exe` file that was just downloaded
* Go to the [RStudio download page](https://posit.co/download/rstudio-desktop/)
* Follow the link to download the latest version under "Install Rstudio" 
* Double click the file to install it
* Once it's installed, open RStudio to make sure it works and you don't get any
  error messages.

### Linux {-}

* Follow the instructions for your distribution
  from [CRAN](https://cloud.r-project.org/bin/linux), they provide information
  to get the most recent version of R for common distributions. For most
  distributions, you could use your package manager (e.g., for Debian/Ubuntu run
  `sudo apt-get install r-base`, and for Fedora `sudo yum install R`), but we
  don't recommend this approach as the versions provided by this are
  usually out of date. In any case, make sure you have at least R 4.0.0.
* Go to the [RStudio download page](https://posit.co/download/rstudio-desktop/)
* Follow the link to download the latest version under "Install Rstudio" 
* Once it's installed, open RStudio to make sure it works and you don't get any
  error messages.


## Acknowledgements {-}
Part of the materials for this tutorial are adapted from http://datacarpentry.org and http://softwarecarpentry.org.
